--Place this file in your .xmonad/lib directory and import module Colors into .xmonad/xmonad.hs config
--The easy way is to create a soft link from this file to the file in .xmonad/lib using ln -s
--Then recompile and restart xmonad.

module Colors
    ( wallpaper
    , background, foreground, cursor
    , color0, color1, color2, color3, color4, color5, color6, color7
    , color8, color9, color10, color11, color12, color13, color14, color15
    ) where

-- Shell variables
-- Generated by 'wal'
wallpaper="/home/beach/.local/share/misty-nagano.jpg"

-- Special
background="#0a0a08"
foreground="#dfdfdf"
cursor="#dfdfdf"

-- Colors
color0="#0a0a08"
color1="#6F6F6D"
color2="#8C6F2C"
color3="#7C8163"
color4="#928951"
color5="#969593"
color6="#C5BBB5"
color7="#dfdfdf"
color8="#9c9c9c"
color9="#6F6F6D"
color10="#8C6F2C"
color11="#7C8163"
color12="#928951"
color13="#969593"
color14="#C5BBB5"
color15="#dfdfdf"
