# Shell variables
# Generated by 'wal'
wallpaper='/home/beach/.local/share/misty-nagano.jpg'

# Special
background='#0a0a08'
foreground='#dfdfdf'
cursor='#dfdfdf'

# Colors
color0='#0a0a08'
color1='#6F6F6D'
color2='#8C6F2C'
color3='#7C8163'
color4='#928951'
color5='#969593'
color6='#C5BBB5'
color7='#dfdfdf'
color8='#9c9c9c'
color9='#6F6F6D'
color10='#8C6F2C'
color11='#7C8163'
color12='#928951'
color13='#969593'
color14='#C5BBB5'
color15='#dfdfdf'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
